OnlineStore.Web/Areas/Admin/Controllers/ShippingAddressesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Data.Entities;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Services.BLL.Services;
using OnlineStore.Data.Interfaces;
using OnlineStore.Common;

namespace OnlineStore.Web.Areas.Admin.Controllers
{
    public class ShippingAddressesController : Controller
    {
        private readonly CityService _cityService;
        private readonly CustomerService _customerService;
        private readonly ShippingAddressService _shippingAddressService;

        public ShippingAddressesController()
        {
            this._cityService = new CityService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._customerService = new CustomerService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._shippingAddressService = new ShippingAddressService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }


        // GET: Admin/Addresses
        public ActionResult Index()
        {
            return View();
        }

        // GET: List of customer
        public ActionResult _List(SortingPagingInfo info, DefaultFilter filter)
        {
            if (info.SortField == null)
            {
                info = new SortingPagingInfo
                {
                    SortField = "Name",
                    SortDirection = "ascending",
                    PageSize = CommonConstants.PAGE_SIZE,
                    CurrentPage = 1
                };
            }

            _shippingAddressService.Pagination = info;
            _shippingAddressService.Filter = filter;
            var addresses = _shippingAddressService.GetShippingAddresses();
            TempData["SortingPagingInfo"] = _shippingAddressService.Pagination;

            return PartialView(addresses);
        }

        // GET: Admin/Addresses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var shippingAddress = _shippingAddressService.GetShippingAddress(id);
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }
            return View(shippingAddress);
        }

        // GET: Admin/Addresses/Create
        public ActionResult Create()
        {
            ViewBag.Cities = GetCities();
            ViewBag.Customers = GetCustomers();
            return View();
        }

        // POST: Admin/Addresses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ShippingAddress shippingAddress)
        {
            if (ModelState.IsValid)
            {
                UpdateDefaultProperties(shippingAddress);
                _shippingAddressService.CreateShippingAddress(shippingAddress);
                return RedirectToAction("Index");
            }
            return View(shippingAddress);
        }

        // GET: Admin/Addresses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var shippingAddress = _shippingAddressService.GetShippingAddress(id);
            ViewBag.Cities = GetCities();
            ViewBag.Customers = GetCustomers();
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }
            return View(shippingAddress);
        }

        // POST: Admin/Addresses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ShippingAddress shippingAddress)
        {
            if (ModelState.IsValid)
            {
                UpdateDefaultProperties(shippingAddress);
                _shippingAddressService.UpdateShippingAddress(shippingAddress);
                return RedirectToAction("Index");
            }
            return View(shippingAddress);
        }

        // GET: Admin/Addresses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var shippingAddress = _shippingAddressService.GetShippingAddress(id);
            if (shippingAddress == null)
            {
                return HttpNotFound();
            }
            return View(shippingAddress);
        }

        // POST: Admin/Addresses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _shippingAddressService.DeleteShippingAddress(id);
            return RedirectToAction("Index");
        }

        // Get cities
        public List<City> GetCities()
        {
            _cityService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 0
            };
            return _cityService.GetCities();
        }

        // Get customers
        public List<Customer> GetCustomers()
        {
            _customerService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 0
            };
            return _customerService.GetCustomers();
        }

        // Update: CreatedOn, CreatedBy, ModifiedOn, ModifiedBy
        public void UpdateDefaultProperties(ShippingAddress shippingAddress)
        {
            var user = Session[CommonConstants.USER_SESSION] as User;
            // Create
            if (user != null)
            {
                if (shippingAddress.Id == 0)
                {
                    shippingAddress.CreatedById = user.Id;
                    shippingAddress.CreatedOn = DateTime.Now;
                    shippingAddress.ModifiedById = user.Id;
                    shippingAddress.ModifiedOn = DateTime.Now;
                }
                // Update
                else
                {
                    shippingAddress.ModifiedById = user.Id;
                    shippingAddress.ModifiedOn = DateTime.Now;
                }
            }
        }
    }
}

OnlineStore.Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Common;

namespace OnlineStore.Web.Controllers
{
    public class CommonController : Controller
    {
        public ActionResult ButtonCreate()
        {
            return PartialView();
        }

        public ActionResult ButtonSave(string elementId)
        {
            ViewBag.ElementId = string.IsNullOrEmpty(elementId) ? "btnSumit" : ("btnSumit-" + elementId);
            return PartialView();
        }

        public ActionResult ButtonCommon(string title, string script)
        {
            ViewBag.Title = title;
            ViewBag.Script = script;

            return PartialView();
        }

        public ActionResult ButtonCancel()
        {
            return PartialView();
        }

        public ActionResult ButtonEdit()
        {
            return PartialView();
        }

        public ActionResult ButtonClear()
        {
            return PartialView();
        }

        public ActionResult ButtonDelete()
        {
            return PartialView();
        }

        public ActionResult UploadImage(string avatar)
        {
            ViewBag.Avatar = avatar;
            return PartialView();
        }

        public ActionResult Paging(string totalRows, string currentPage, string pageSize, string controlName)
        {
            var currentPageFilter = int.Parse(currentPage);
            var pageSizeFilter = int.Parse(pageSize);

            ViewBag.ControlName = controlName;

            if (pageSizeFilter == 0)
            {
                ViewBag.TotalPage = 1;
            }
            else
            {
                if (int.Parse(totalRows) % pageSizeFilter == 0)
                {
                    ViewBag.TotalPage = int.Parse(totalRows) / pageSizeFilter;
                }
                else
                {
                    ViewBag.TotalPage = (int.Parse(totalRows) / pageSizeFilter) + 1;
                }
                if (ViewBag.TotalPage < (pageSizeFilter + 1))
                {
                    ViewBag.StartNumber = 1;
                    ViewBag.EndNumber = ViewBag.TotalPage;
                }
                else
                {
                    int subtract = 0;
                    int plus = 0;
                    if (currentPageFilter == 1)
                    {
                        subtract = 0;
                        plus = 4;
                    }
                    else if (currentPageFilter == 2)
                    {
                        subtract = 1;
                        plus = 3;
                    }
                    else if (currentPageFilter <= ViewBag.TotalPage - 2)
                    {
                        subtract = 2;
                        plus = 2;
                    }
                    else if (currentPageFilter == ViewBag.TotalPage - 1)
                    {
                        subtract = 3;
                        plus = 1;
                    }
                    else if (currentPageFilter == ViewBag.TotalPage)
                    {
                        subtract = 4;
                        plus = 0;
                    }
                    ViewBag.StartNumber = currentPageFilter - subtract;
                    ViewBag.EndNumber = currentPageFilter + plus;
                }
            }

            ViewBag.CurrentPage = currentPageFilter;
            ViewBag.TotalRows = totalRows;
            ViewBag.PageSize = pageSize;

            return PartialView();
        }

        public ActionResult _Paging(string totalRows, string currentPage, string pageSize, string controlName)
        {
            var currentPageFilter = int.Parse(currentPage);
            var pageSizeFilter = int.Parse(pageSize);

            ViewBag.ControlName = controlName;

            if (pageSizeFilter == 0)
            {
                ViewBag.TotalPages = 1;
            }
            else
            {
                if (int.Parse(totalRows) % pageSizeFilter == 0)
                {
                    ViewBag.TotalPages = int.Parse(totalRows) / pageSizeFilter;
                }
                else
                {
                    ViewBag.TotalPages = (int.Parse(totalRows) / pageSizeFilter) + 1;
                }
                if (ViewBag.TotalPages < (pageSizeFilter + 1))
                {
                    ViewBag.StartNumber = 1;
                    ViewBag.EndNumber = ViewBag.TotalPages;
                }
                else
                {
                    int subtract = 0;
                    int plus = 0;
                    if (currentPageFilter == 1)
                    {
                        subtract = 0;
                        plus = 4;
                    }
                    else if (currentPageFilter == 2)
                    {
                        subtract = 1;
                        plus = 3;
                    }
                    else if (currentPageFilter <= ViewBag.TotalPages - 2)
                    {
                        subtract = 2;
                        plus = 2;
                    }
                    else if (currentPageFilter == ViewBag.TotalPages - 1)
                    {
                        subtract = 3;
                        plus = 1;
                    }
                    else if (currentPageFilter == ViewBag.TotalPages)
                    {
                        subtract = 4;
                        plus = 0;
                    }
                    ViewBag.StartNumber = currentPageFilter - subtract;
                    ViewBag.EndNumber = currentPageFilter + plus;
                }
            }

            ViewBag.CurrentPage = currentPageFilter;
            ViewBag.TotalRows = totalRows;
            ViewBag.PageSize = pageSize;
            ViewBag.FromRecord = currentPageFilter * pageSizeFilter - pageSizeFilter + 1;
            ViewBag.ToRecord = currentPageFilter * pageSizeFilter;

            return PartialView();
        }
    }
}

OnlineStore.Web/Areas/Admin/Views/ShippingAddresses/Create.cshtml
<script src="~/assets/admin/js/jquery-ui.min.js"></script>
<link href="~/assets/admin/css/jquery-ui.min.css" rel="stylesheet" />
<script src="~/assets/admin/js/app/shipping-address/edit.js"></script>
@using OnlineStore.Data.Entities
@model OnlineStore.Data.Entities.ShippingAddress
@{
    ViewBag.Module = "Địa chỉ giao hàng";
    ViewBag.Title = "Tạo mới";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="CustomerId" class="slCustomer form-control">
                    @{
                        var customers = (List<Customer>)ViewBag.Customers;

                        foreach (var customer in customers)
                        {
                            <option value="@customer.Id">@customer.Name</option>
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Value, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Value, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Value, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <select name="CityId" class="slCity form-control">
                    @{
                        var cities = (List<City>)ViewBag.Cities;

                        foreach (var city in cities)
                        {
                            <option value="@city.Id">@city.Name</option>
                        }
                    }
                </select>
                @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Note, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-white btn-info btn-bold">
                    <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
                    Lưu lại
                </button>
            </div>
        </div>
    </div>
}

<div>
    <i class="ace-icon fa fa-reply icon-only"></i> @Html.ActionLink("Trở về trang chủ", "Index")
</div>

<script>
    $(document).ready(function () {
        $(".slCustomer").select2({
            placeholder: "Chọn khách hàng",
            allowClear: true
        });

        $(".slCity").select2({
            placeholder: "Chọn thành phố",
            allowClear: true
        });
    });
</script>

OnlineStore.Web/Areas/Admin/Views/ShippingAddresses/Delete.cshtml
@model OnlineStore.Data.Entities.ShippingAddress
@{
    ViewBag.Module = "Địa chỉ giao hàng";
    ViewBag.Title = "Xóa địa chỉ";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="alert alert-danger">
    Bạn có chắc muốn xóa địa chỉ giao hàng này?
</div>

<div>
    @*Details information*@
    <div class="widget-box">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">Thông tin chi tiết</h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CustomerId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Customer.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Value)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Value)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.PostalCode)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PostalCode)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CityId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.City.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Telephone)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Telephone)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Note)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Note)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    @*Common information*@
    <div class="widget-box">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">Thông tin chung</h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedOn)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedOn)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedBy)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedBy.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ModifiedOn)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ModifiedOn)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ModifiedBy)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ModifiedBy.Name)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <button type="submit" class="btn btn-white btn-danger btn-bold">
        <i class="ace-icon fa fa-floppy-o bigger-120 red"></i>
        Xác nhận
    </button>
}

<div style="padding-top: 20px;">
    <i class="ace-icon fa fa-reply icon-only"></i> @Html.ActionLink("Trở về trang chủ", "Index")
</div>

OnlineStore.Web/Areas/Admin/Views/ShippingAddresses/Details.cshtml
@model OnlineStore.Data.Entities.ShippingAddress
@{
    ViewBag.Module = "Địa chỉ giao hàng";
    ViewBag.Title = "Chi tiết";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div>
    @*Details information*@
    <div class="widget-box">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">Thông tin chi tiết</h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CustomerId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Customer.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Value)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Value)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.PostalCode)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PostalCode)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CityId)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.City.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Telephone)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Telephone)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.Note)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Note)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
    @*Common information*@
    <div class="widget-box">
        <div class="widget-header widget-header-flat">
            <h4 class="widget-title smaller">Thông tin chung</h4>
        </div>
        <div class="widget-body">
            <div class="widget-main">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedOn)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedOn)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedBy)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.CreatedBy.Name)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ModifiedOn)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ModifiedOn)
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model.ModifiedBy)
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.ModifiedBy.Name)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
</div>
<p>
    <button class="btn btn-white btn-info btn-bold">
        <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
        @Html.ActionLink("Chỉnh sửa", "Edit", new { id = Model.Id })
    </button>
    <div style="padding-top: 20px;">
        <i class="ace-icon fa fa-reply icon-only"></i> @Html.ActionLink("Trở về trang chủ", "Index")
    </div>
</p>

OnlineStore.Web/Areas/Admin/Views/ShippingAddresses/Index.cshtml
@model IEnumerable<OnlineStore.Data.Entities.ShippingAddress>
@{
    ViewBag.Module = "Địa chỉ giao hàng";
    ViewBag.Title = "Danh sách";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}
<div class="action-buttons" style="padding-bottom: 10px;">
    <button class="btn btn-white btn-info btn-bold">
        <i class="ace-icon fa fa-floppy-o bigger-120 blue"></i>
        @Html.ActionLink("Tạo mới", "Create")
    </button>
    @Html.Partial("_Search")
    <input type="hidden" id="hdControllerName" value="Addresses" />
</div>
<div id="search-container">
    @Html.Action("_List", "ShippingAddresses")
</div>

OnlineStore.Web/Areas/Admin/Views/ShippingAddresses/_List.cshtml
<script src="~/assets/admin/js/jquery.2.1.1.min.js"></script>
<script src="~/assets/admin/js/app/shipping-address/list.js"></script>
@using OnlineStore.Common
@model IEnumerable<OnlineStore.Data.Entities.ShippingAddress>
@{
    var info = (SortingPagingInfo)TempData["SortingPagingInfo"];
}
<div class="row">
    <div class="col-xs-12">
        <table id="dynamic-table" class="table table-striped table-bordered table-hover dataTable">
            <thead>
                <tr>
                    <th class="sorting sortable" data-sortfield="CustomerId">
                        @Html.DisplayNameFor(model => model.CustomerId)
                    </th>
                    <th class="sorting sortable" data-sortfield="CustomerId">
                        @Html.DisplayNameFor(model => model.Value)
                    </th>
                    <th class="sorting sortable" data-sortfield="PostalCode">
                        @Html.DisplayNameFor(model => model.PostalCode)
                    </th>
                    <th class="sorting sortable" data-sortfield="CityId">
                        @Html.DisplayNameFor(model => model.CityId)
                    </th>
                    <th class="sorting sortable" data-sortfield="Telephone">
                        @Html.DisplayNameFor(model => model.Telephone)
                    </th>
                    <th class="sorting sortable" data-sortfield="Note">
                        @Html.DisplayNameFor(model => model.Note)
                    </th>
                    <th class="sorting_disabled"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="~/Admin/ShippingAddresses/Details/@item.Id">
                                @Html.DisplayFor(modelItem => item.Customer.Name)
                            </a>
                        </td>
                        <td>
                            @Html.ValueFor(modelItem => item.Value)
                        </td>
                        <td>
                            @Html.ValueFor(modelItem => item.PostalCode)
                        </td>
                        <td>
                            @Html.ValueFor(modelItem => item.City.Name)
                        </td>
                        <td>
                            @Html.ValueFor(modelItem => item.Telephone)
                        </td>
                        <td>
                            @Html.ValueFor(modelItem => item.Note)
                        </td>
                        <td>
                            <div class="hidden-sm hidden-xs action-buttons">
                                <a class="blue" href="~/Admin/ShippingAddresses/Details/@item.Id">
                                    <i class="ace-icon fa fa-search-plus bigger-130"></i>
                                </a>
                                <a class="green" href="~/Admin/ShippingAddresses/Edit/@item.Id">
                                    <i class="ace-icon fa fa-pencil bigger-130"></i>
                                </a>
                                <a class="red" href="~/Admin/ShippingAddresses/Delete/@item.Id">
                                    <i class="ace-icon fa fa-trash-o bigger-130"></i>
                                </a>
                            </div>
                            <div class="hidden-md hidden-lg">
                                <div class="inline pos-rel">
                                    <button class="btn btn-minier btn-primary dropdown-toggle" data-toggle="dropdown" data-position="auto">
                                        <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                                    </button>
                                    <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                        <li>
                                            <a href="~/Admin/ShippingAddresses/Details/@item.Id" class="tooltip-info" data-rel="tooltip" title="View">
                                                <span class="blue">
                                                    <i class="ace-icon fa fa-search-plus bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="~/Admin/ShippingAddresses/Edit/@item.Id" class="tooltip-success" data-rel="tooltip" title="Edit">
                                                <span class="green">
                                                    <i class="ace-icon fa fa-pencil-square-o bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="~/Admin/ShippingAddresses/Delete/@item.Id" class="tooltip-error" data-rel="tooltip" title="Delete">
                                                <span class="red">
                                                    <i class="ace-icon fa fa-trash-o bigger-120"></i>
                                                </span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@Html.Action("_Paging", "Common", new { totalRows = info.TotalRows, currentPage = info.CurrentPage, pageSize = info.PageSize, controlName = "/ShippingShippingAddresses/Index" })