OnlineStore.Web/Areas/Admin/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Common;
using OnlineStore.Data.Entities;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Data.Interfaces;
using OnlineStore.Services.BLL.Services;

namespace OnlineStore.Web.Areas.Admin.Controllers
{
    public class SubCategoriesController : BaseController
    {
        private readonly SubCategoryService _subCategoryService;
        private readonly CategoryService _categoryService;

        public SubCategoriesController()
        {
            this._subCategoryService = new SubCategoryService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._categoryService = new CategoryService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        // GET: Admin/SubCategories
        public ActionResult Index()
        {
            return View();
        }

        // GET: List of sub categories
        public ActionResult _List(SortingPagingInfo info, DefaultFilter filter)
        {
            if (info.SortField == null)
            {
                info = new SortingPagingInfo
                {
                    SortField = "Name",
                    SortDirection = "ascending",
                    PageSize = CommonConstants.PAGE_SIZE,
                    CurrentPage = 1
                };
            }

            _subCategoryService.Pagination = info;
            _subCategoryService.Filter = filter;
            var subCategories = _subCategoryService.GetSubCategories();
            TempData["SortingPagingInfo"] = _subCategoryService.Pagination;

            return PartialView(subCategories);
        }

        // GET: Admin/SubCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subCategory = _subCategoryService.GetSubCategory(id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // GET: Admin/SubCategories/Create
        public ActionResult Create()
        {
            ViewBag.Categories = GetCategories();
            return View();
        }

        // POST: Admin/SubCategories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                UpdateDefaultProperties(subCategory);
                _subCategoryService.CreateSubCategory(subCategory);
                return RedirectToAction("Index");
            }

            return View(subCategory);
        }

        // GET: Admin/SubCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subCategory = _subCategoryService.GetSubCategory(id);
            ViewBag.Categories = GetCategories();
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // POST: Admin/SubCategories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SubCategory subCategory)
        {
            if (ModelState.IsValid)
            {
                UpdateDefaultProperties(subCategory);
                _subCategoryService.UpdateSubCategory(subCategory);
                return RedirectToAction("Index");
            }
            
            return View(subCategory);
        }

        // GET: Admin/SubCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var subCategory = _subCategoryService.GetSubCategory(id);
            if (subCategory == null)
            {
                return HttpNotFound();
            }
            return View(subCategory);
        }

        // POST: Admin/SubCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            _subCategoryService.DeleteSubCategory(id);
            return RedirectToAction("Index");
        }

        // Update: CreatedOn, CreatedBy, ModifiedOn, ModifiedBy
        public void UpdateDefaultProperties(SubCategory subCategory)
        {
            var user = Session[CommonConstants.USER_SESSION] as User;
            // Create
            if (user != null)
            {
                if (subCategory.Id == 0)
                {
                    subCategory.CreatedById = user.Id;
                    subCategory.CreatedOn = DateTime.Now;
                    subCategory.ModifiedById = user.Id;
                    subCategory.ModifiedOn = DateTime.Now;
                }
                // Update
                else
                {
                    subCategory.ModifiedById = user.Id;
                    subCategory.ModifiedOn = DateTime.Now;
                }
            }
        }

        // Get categories
        public List<Category> GetCategories()
        {
            _categoryService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 0
            };
            return _categoryService.GetCategories();
        }
    }
}

OnlineStore.Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Common;

namespace OnlineStore.Web.Controllers
{
    public class CommonController : Controller
    {
        public ActionResult ButtonCreate()
        {
            return PartialView();
        }

        public ActionResult ButtonSave(string elementId)
        {
            ViewBag.ElementId = string.IsNullOrEmpty(elementId) ? "btnSumit" : ("btnSumit-" + elementId);
            return PartialView();
        }

        public ActionResult ButtonCommon(string title, string script)
        {
            ViewBag.Title = title;
            ViewBag.Script = script;

            return PartialView();
        }

        public ActionResult ButtonCancel()
        {
            return PartialView();
        }

        public ActionResult ButtonEdit()
        {
            return PartialView();
        }

        public ActionResult ButtonClear()
        {
            return PartialView();
        }

        public ActionResult ButtonDelete()
        {
            return PartialView();
        }

        public ActionResult UploadImage(string avatar)
        {
            ViewBag.Avatar = avatar;
            return PartialView();
        }

        public ActionResult Paging(string totalRows, string currentPage, string pageSize, string controlName)
        {
            var currentPageFilter = int.Parse(currentPage);
            var pageSizeFilter = int.Parse(pageSize);

            ViewBag.ControlName = controlName;

            if (pageSizeFilter == 0)
            {
                ViewBag.TotalPage = 1;
            }
            else
            {
                if (int.Parse(totalRows) % pageSizeFilter == 0)
                {
                    ViewBag.TotalPage = int.Parse(totalRows) / pageSizeFilter;
                }
                else
                {
                    ViewBag.TotalPage = (int.Parse(totalRows) / pageSizeFilter) + 1;
                }
                if (ViewBag.TotalPage < (pageSizeFilter + 1))
                {
                    ViewBag.StartNumber = 1;
                    ViewBag.EndNumber = ViewBag.TotalPage;
                }
                else
                {
                    int subtract = 0;
                    int plus = 0;
                    if (currentPageFilter == 1)
                    {
                        subtract = 0;
                        plus = 4;
                    }
                    else if (currentPageFilter == 2)
                    {
                        subtract = 1;
                        plus = 3;
                    }
                    else if (currentPageFilter <= ViewBag.TotalPage - 2)
                    {
                        subtract = 2;
                        plus = 2;
                    }
                    else if (currentPageFilter == ViewBag.TotalPage - 1)
                    {
                        subtract = 3;
                        plus = 1;
                    }
                    else if (currentPageFilter == ViewBag.TotalPage)
                    {
                        subtract = 4;
                        plus = 0;
                    }
                    ViewBag.StartNumber = currentPageFilter - subtract;
                    ViewBag.EndNumber = currentPageFilter + plus;
                }
            }

            ViewBag.CurrentPage = currentPageFilter;
            ViewBag.TotalRows = totalRows;
            ViewBag.PageSize = pageSize;

            return PartialView();
        }

        public ActionResult _Paging(string totalRows, string currentPage, string pageSize, string controlName)
        {
            var currentPageFilter = int.Parse(currentPage);
            var pageSizeFilter = int.Parse(pageSize);

            ViewBag.ControlName = controlName;

            if (pageSizeFilter == 0)
            {
                ViewBag.TotalPages = 1;
            }
            else
            {
                if (int.Parse(totalRows) % pageSizeFilter == 0)
                {
                    ViewBag.TotalPages = int.Parse(totalRows) / pageSizeFilter;
                }
                else
                {
                    ViewBag.TotalPages = (int.Parse(totalRows) / pageSizeFilter) + 1;
                }
                if (ViewBag.TotalPages < (pageSizeFilter + 1))
                {
                    ViewBag.StartNumber = 1;
                    ViewBag.EndNumber = ViewBag.TotalPages;
                }
                else
                {
                    int subtract = 0;
                    int plus = 0;
                    if (currentPageFilter == 1)
                    {
                        subtract = 0;
                        plus = 4;
                    }
                    else if (currentPageFilter == 2)
                    {
                        subtract = 1;
                        plus = 3;
                    }
                    else if (currentPageFilter <= ViewBag.TotalPages - 2)
                    {
                        subtract = 2;
                        plus = 2;
                    }
                    else if (currentPageFilter == ViewBag.TotalPages - 1)
                    {
                        subtract = 3;
                        plus = 1;
                    }
                    else if (currentPageFilter == ViewBag.TotalPages)
                    {
                        subtract = 4;
                        plus = 0;
                    }
                    ViewBag.StartNumber = currentPageFilter - subtract;
                    ViewBag.EndNumber = currentPageFilter + plus;
                }
            }

            ViewBag.CurrentPage = currentPageFilter;
            ViewBag.TotalRows = totalRows;
            ViewBag.PageSize = pageSize;
            ViewBag.FromRecord = currentPageFilter * pageSizeFilter - pageSizeFilter + 1;
            ViewBag.ToRecord = currentPageFilter * pageSizeFilter;

            return PartialView();
        }
    }
}

OnlineStore.Web/Controllers/SubCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Common;
using OnlineStore.Data.Entities;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Services.BLL.Services;
using OnlineStore.Data.Interfaces;

namespace OnlineStore.Web.Controllers
{
    public class SubCategoriesController : Controller
    {
        private readonly SubCategoryService _subCategoryService;
        private readonly ProductService _productService;
        private readonly BrandService _brandService;

        public SubCategoriesController()
        {
            this._subCategoryService = new SubCategoryService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._productService = new ProductService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._brandService = new BrandService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        private OnlineStoreDbContext db = new OnlineStoreDbContext();

        // GET: SubCategories
        public ActionResult Index(int? id)
        {
            var subCategories = db.SubCategories.Include(s => s.Category).Include(s => s.CreatedBy).Include(s => s.ModifiedBy);
            return View(subCategories.ToList());
        }

        // GET: List of products
        public ActionResult _List(SortingPagingInfo info, DefaultFilter filter)
        {
            if (info.SortField == null)
            {
                info = new SortingPagingInfo
                {
                    SortField = "Title",
                    SortDirection = "ascending",
                    PageSize = CommonConstants.PAGE_SIZE,
                    CurrentPage = 1
                };
            }

            _productService.Pagination = info;
            _productService.Filter = filter;
            var products = _productService.GetProducts();
            TempData["SortingPagingInfo"] = _productService.Pagination;

            return PartialView(products);
        }

        // GET: SubCategories/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.SubCategoryId = id;
            var subCategory = _subCategoryService.GetSubCategory(id);
            return View(subCategory);
        }

        // Related brands
        public ActionResult _RelatedBrands(int? subCategoryId)
        {
            _brandService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 10
            };

            _brandService.Filter = new DefaultFilter()
            {
                SubCategoryId = subCategoryId == null ? 0 : subCategoryId.Value
            };

            var brands = _brandService.GetBrands();

            return PartialView(brands);
        }

        //Filter
        public ActionResult _Filter(int? subCategoryId)
        {
            ViewBag.SubCategoryId = subCategoryId;

            return PartialView();
        }
    }
}

OnlineStore.Web/Views/SubCategories/Details.cshtml
@model OnlineStore.Data.Entities.SubCategory

@{
    <!--For Breadcrumb-->
    ViewBag.BreadcrumbType = "SubCategory";
    ViewBag.ObjectId = Model.Id;
}

<!--Hidden fields-->
<input type="hidden" id="hdControllerName" value="Categories" />

<!--Hidden search-->
@Html.Partial("_HiddenSearch")

<div class="main">
    <div class="container">
        <div class="row">

            @*@Html.Partial("_Filter")*@

            @Html.Action("_Filter", "SubCategories", new { subCategoryId = Model.Id })

            <div class="col-sm-9 col-right">
                <div class="banner">
                    <a href="#"><img alt="" src="~/assets/web/images/ads/ads-17.jpg"></a>
                </div>
                <div class="page-title">
                    <h1>TÊN DANH MỤC</h1>
                </div>
                <div class="toolbar">
                    <div class="sorter">
                        <p class="view-mode">
                            <label>Xem đưới dạng:</label>
                            <a class="grid view-selected" onclick="toggleViewMode();" title="Grid">Lưới</a>&nbsp;
                            <a class="list" onclick="toggleViewMode();" title="List" href="#">Danh sách</a>&nbsp;
                        </p>
                    </div><!-- /.sorter -->
                    <div class="pager">
                        <div class="sort-by hidden-xs">
                            <label>Sắp xếp theo:</label>
                            <select id="slSorting" class="form-control input-sm">
                                <option value="Name-ascending" selected="selected">Tên: Từ A-Z</option>
                                <option value="Name-descending">Tên: Từ Z-A</option>
                                <option value="Price-ascending">Giá: Từ nhỏ nhất đến lớn nhất</option>
                                <option value="Price-descending">Giá: Từ lớn nhất đến nhỏ nhất</option>
                            </select>
                            <span id="sorting-ascending" class="fa fa-sort-amount-asc"></span>
                            <span id="sorting-descending" style="display:none;" class="fa fa-sort-amount-desc"></span>
                        </div>
                    </div><!--- /.pager -->
                </div><!-- /.toolbar -->

                <div id="search-container">
                    @Html.Action("_List", "Categories", new { SubCategoryId = Model.Id })
                </div>
            </div><!-- /.col-right -->
        </div>
    </div>
</div>


<style>
    .view-selected, .view-selected:before {
        color: #fff !important;
        background: #d8373e;
        border-color: #d8373e;
    }

    .pager .sort-by {
        border-left: 0px;
        border-right: 0px;
    }
</style>

<script>
    $(document).ready(function () {
        /* slider price */
        var currencies = "$";
        var toolbar_status = "1";
        var rate = "1";
        var min = "99"
        min = Number(min);
        var max = "999"
        max = Number(max);
        var currentMinPrice = "99"
        currentMinPrice = Number(currentMinPrice);
        var currentMaxPrice = "999"
        //alert('min: '+min+'--max: '+ max+ 'currentMin: '+currentMinPrice);
        currentMaxPrice = Number(currentMaxPrice);
        var params = "";
        params = $.trim(params);
        //slider
        $("#slider-range").slider({
            range: true,
            min: min,
            max: max,
            values: [currentMinPrice, currentMaxPrice],
            slide: function (event, ui) {
                $("#amount").val(currencies + ui.values[0] + " - " + currencies + ui.values[1]);
                $('input[name="first_price"]').val(ui.values[0]);
                $('input[name="last_price"]').val(ui.values[1]);
            },
            stop: function (event, ui) {
            }
        });

        $("#amount").val(currencies + $("#slider-range").slider("values", 0) +
            " - " + currencies + $("#slider-range").slider("values", 1));
        $('input[name="first_price"]').val($("#slider-range").slider("values", 0));
        $('input[name="last_price"]').val($("#slider-range").slider("values", 1));

        //search price from input box
        //$('#search_price').each(function () {
        //    $(this).live('click', function () {
        //        return false;
        //    })
        //});
        //$('#slider-range a:first').addClass('first_item');
        //$('#slider-range a:last').addClass('last_item');

        //Paging
        LoadSorting();

        $("#slSorting").change(function () {
            var sortArr = $(this).val().split("-");
            var sortField = sortArr[0];
            var sortDirection = sortArr[1];

            $("#hdSortField").val(sortField);
            $("#hdSortDirection").val(sortDirection);

            fnSearchWeb();
        });
    });

    function LoadSorting() {
        var sortDirection = $("#hdSortDirection").val();

        if (sortDirection === "ascending") {
            $("#sorting-ascending").show();
            $("#sorting-descending").hide();
        }
        else {
            $("#sorting-ascending").hide();
            $("#sorting-descending").show();
        }
    }

    function toggleViewMode() {
        $("#viewmode-grid").toggle();
        $("#viewmode-list").toggle();

        $(".grid").toggleClass("view-selected");
        $(".list").toggleClass("view-selected");
    }
</script>

OnlineStore.Web/Views/SubCategories/Index.cshtml
@model IEnumerable<OnlineStore.Data.Entities.SubCategory>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedBy.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedBy.Username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrderNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedOn)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedBy.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedBy.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.OrderNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreatedOn)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ModifiedOn)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

OnlineStore.Web/Views/SubCategories/_Filter.cshtml
<div class="col-sm-3 col-left">
    <div class="block block-layered-nav">
        <div class="block-content">
            <div id="narrow-by-list">
                <div class="layered layered-price">
                    <h2>Giá sản phẩm</h2>
                    <div class="content-shopby form-horizontal" style="text-align:center;">
                        <div class="form-group" style="margin-bottom:5px;">
                            <label class="control-label col-sm-2">Từ:</label>
                            <div class="input-group col-sm-10" style="padding:0px 15px;">
                                <input type="number" class="form-control" id="from-price" placeholder="">
                                <div class="input-group-addon">đ</div>
                            </div>
                        </div>
                        <div class="form-group" style="margin-bottom:5px;">
                            <label class="control-label col-sm-2">Đến:</label>
                            <div class="input-group col-sm-10" style="padding:0px 15px;">
                                <input type="number" class="form-control" id="to-price" placeholder="">
                                <div class="input-group-addon">đ</div>
                            </div>
                        </div>
                        <button id="search_price" onclick="SearchByPrices()" name="search_price" type="button" class="btn btn-default">Lọc</button>
                    </div>
                </div>
                <!--Related brands-->
                @Html.Action("_RelatedBrands", "SubCategories", new { subCategoryId = ViewBag.SubCategoryId })
            </div>
        </div>
    </div><!-- /sort -->
</div><!-- /.col-left -->

<script>
    function SearchByPrices() {
        var fromPrice = $("#from-price").val();
        var toPrice = $("#to-price").val();
        $("#hdPriceRange").val(fromPrice + ":" + toPrice);
        fnSearchWeb();
    }
</script>

OnlineStore.Web/Views/SubCategories/_List.cshtml
@using OnlineStore.Common
@model List<OnlineStore.Data.Entities.Product>
@{
    var info = (SortingPagingInfo)TempData["SortingPagingInfo"];
}

@*Grid*@
<div id="viewmode-grid">
    <div class="row products">
        @foreach (var product in Model)
        {
            var featuredImage = product.ProductPhotos.FirstOrDefault(x => x.Featured == true);
            var featuredImageUrl = Placeholder.PRODUCT;
            if (featuredImage != null)
            {
                featuredImageUrl = featuredImage.Photo.Url;
            }

            <div class="col-md-3 col-sm-6">
                <div class='productslider-item item'>
                    <div class="item-inner">
                        <div class="~/assets/web/images-container">
                            <div class="product_icon">
                                <div class='new-icon'><span>new</span></div>
                                <div class="sale-icon"><span>sale</span></div>
                            </div>
                            <a href="/san-pham/@product.MetaTitle-@product.Id" title="@product.Name" class="product-image">
                                <img src="~/@featuredImageUrl" alt="@product.Name" />
                            </a>
                        </div>
                        <div class="des-container">
                            <h2 class="product-name">
                                <a href="/san-pham/@product.MetaTitle-@product.Id" title="@product.Name">@product.Name</a>
                            </h2>
                            <div class="price-box">
                                <p class="special-price">
                                    <span class="price">@product.Price.ToCurrency() đ</span>
                                </p>
                                @*<p class="old-price">
                                    <span class="price">190.000 đ</span>
                                </p>*@
                            </div>
                        </div>
                        <div class="cart-container">
                            <button type="submit" class="btn btn-danger btn-cart">Mua</button>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div><!-- /.product -->
</div>

@*List*@
<div id="viewmode-list" style="display: none;">
    <ol id="products-list" class="products-list">
        @foreach (var product in Model)
        {
            var featuredImage = product.ProductPhotos.FirstOrDefault(x => x.Featured == true);
            var featuredImageUrl = Placeholder.PRODUCT;
            if (featuredImage != null)
            {
                featuredImageUrl = featuredImage.Photo.Url;
            }

            <li class="item">
                <div class="item-inner">
                    <div class="row">
                        <div class="col-sm-4 col-sms-4 col-smb-12">
                            <div class="~/assets/web/images-container">
                                <div class="product_icon">
                                    <div class="new-icon"><span>new</span></div>
                                    <div class="sale-icon"><span>sale</span></div>
                                </div>
                                s<a class="product-image" title="@product.Name" href="#" rel="author"><img alt="@product.Name" src="~/@featuredImageUrl"></a>
                            </div>
                        </div>
                        <div class="product-shop col-sm-8 col-sms-8 col-smb-12">
                            <div class="f-fix">
                                <h2 class="product-name">
                                    <a title="" href="#">@product.Name</a>
                                </h2>
                                <div class="price-box">
                                    <p class="special-price">
                                        <span class="price-label">Special Price</span>
                                        <span id="product-price-1" class="price">200.000 đ</span>
                                    </p>
                                    <p class="old-price">
                                        <span class="price-label">Regular Price:</span>
                                        <span id="old-price-1" class="price">190.000 đ</span>
                                    </p>
                                </div>
                                <div class="desc std">
                                    @product.Description <a class="link-learn" title="@product.Name" href="#">Xem hàng</a>
                                </div>
                                <div class="actions">
                                    <div class="actions-inner">
                                        <button class="btn btn-danger" title="Add to Cart" type="button">Mua</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        }
    </ol>
</div>

@Html.Action("_Paging", "Common", new { totalRows = info.TotalRows, currentPage = info.CurrentPage, pageSize = info.PageSize, controlName = "/SubCategories/Index" })