OnlineStore.Web/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Data.Entities;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Services.BLL.Services;
using OnlineStore.Data.Interfaces;
using OnlineStore.Common;

namespace OnlineStore.Web.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ProductService _productService;
        private readonly BrandService _brandService;

        public CategoriesController()
        {
            this._categoryService = new CategoryService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._productService = new ProductService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._brandService = new BrandService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        private OnlineStoreDbContext db = new OnlineStoreDbContext();

        // GET: Categories
        public ActionResult Index(int? id)
        {
            var categories = db.Categories.Include(c => c.CreatedBy).Include(c => c.ModifiedBy);
            return View(categories.ToList());
        }

        // GET: List of products
        public ActionResult _List(SortingPagingInfo info, DefaultFilter filter)
        {
            if (info.SortField == null)
            {
                info = new SortingPagingInfo
                {
                    SortField = "Title",
                    SortDirection = "ascending",
                    PageSize = CommonConstants.PAGE_SIZE,
                    CurrentPage = 1
                };
            }

            _productService.Pagination = info;
            _productService.Filter = filter;
            var products = _productService.GetProducts();
            TempData["SortingPagingInfo"] = _productService.Pagination;

            return PartialView(products);
        }

        // GET: Categories/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.CategoryId = id;
            var category = _categoryService.GetCategory(id);
            return View(category);
        }

        // Get Sub Categories
        public ActionResult _CategorySelection()
        {
            _categoryService.Pagination = new SortingPagingInfo
            {
                SortField = "OrderNumber",
                SortDirection = "ascending",
                PageSize = 0
            };

            ViewBag.Categories = _categoryService.GetCategories();

            return PartialView();
        }

        // Main Menu
        public ActionResult _MainMenu()
        {
            _categoryService.Pagination = new SortingPagingInfo
            {
                SortField = "OrderNumber",
                SortDirection = "ascending",
                PageSize = 0
            };

            ViewBag.Categories = _categoryService.GetCategories();

            return PartialView();
        }

        //Filter
        public ActionResult _Filter(int? categoryId)
        {
            ViewBag.CategoryId = categoryId;

            return PartialView();
        }

        // Related brands
        public ActionResult _RelatedBrands(int? categoryId)
        {
            _brandService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 10
            };

            _brandService.Filter = new DefaultFilter()
            {
                CategoryId = categoryId == null ? 0 : categoryId.Value
            };

            var brands = _brandService.GetBrands();

            return PartialView(brands);
        }
    }
}

OnlineStore.Web/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Data.Interfaces;
using OnlineStore.Services.BLL.Services;

namespace OnlineStore.Web.Controllers
{
    public class MenuController : Controller
    {
        private readonly ModuleService _moduleService;
        private readonly FunctionService _functionService;

        public MenuController()
        {
            this._moduleService = new ModuleService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
            this._functionService = new FunctionService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        // GET: Menu
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TopMenu()
        {
            var modules = _moduleService.GetModules();
            return PartialView(modules);
        }

        public ActionResult SubMenu(string moduleId)
        {
            var functions = _functionService.GetFunctionsByModule(moduleId);
            return PartialView(functions);
        }

        public ActionResult SubMenuList(string moduleId)
        {
            var functions = _functionService.GetFunctionsByModule(moduleId);
            return PartialView(functions);
        }

        // GET: Menu/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Menu/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Menu/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Menu/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Menu/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Menu/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Menu/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OnlineStore.Web/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OnlineStore.Data.Entities;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Services.BLL.Services;
using OnlineStore.Data.Interfaces;
using OnlineStore.Common;

namespace OnlineStore.Web.Controllers
{
    public class MenusController : Controller
    {
        private readonly MenuService _menuService;

        public MenusController()
        {
            this._menuService = new MenuService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        // Get top menu
        public ActionResult _TopMenu()
        {
            _menuService.Pagination = new SortingPagingInfo
            {
                SortField = "Name",
                SortDirection = "ascending",
                PageSize = 0
            };

            ViewBag.Menus = _menuService.GetMenus();

            return PartialView();
        }
    }
}

OnlineStore.Web/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Helpers;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using OnlineStore.Common;
using OnlineStore.Data.Entities;
using OnlineStore.Services.Models;
using OnlineStore.Data.Infrastructure;
using OnlineStore.Data.Interfaces;
using OnlineStore.Services.BLL;
using OnlineStore.Services.BLL.Services;

namespace OnlineStore.Web.Controllers
{
    public class UserController : BaseController
    {
        private readonly UserService _userService;

        public UserController()
        {
            this._userService =  new UserService(new UnitOfWork(new DbContextFactory<OnlineStoreDbContext>()));
        }

        // GET: User
        public ActionResult Index()
        {
            return PartialView();
        }

        // GET: User/Create
        public ActionResult Create(string id)
        {
            var user = new User();
            if (!string.IsNullOrEmpty(id))
            {
                user = _userService.GetUser(id);
            }
            return PartialView(user);
        }

        // POST: User/Create
        [HttpPost]
        public ActionResult Create(User user)
        {
            var jsonModel = new JsonModel<bool>
            {
                ErrorCode = "0",
                ErrorMessage = "",
                Result = true
            };
            try
            {
                if (string.IsNullOrEmpty(user.Id))
                    _userService.CreateUser(user);
                else
                    _userService.UpdateUser(user);
            }
            catch (Exception ex)
            {
                jsonModel.ErrorCode = "-1";
                jsonModel.ErrorMessage = ex.ToString();
                jsonModel.Result = false;
            }
            return Json(jsonModel);
        }

        // GET: User/Details/5
        public ActionResult Details(string id)
        {
            var user = _userService.GetUser(id);
            return PartialView(user);
        }

        // GET: User/Edit/5
        public ActionResult Edit(string id)
        {
            var user = _userService.GetUser(id);
            return PartialView(user);
        }

        // POST: User/Edit/5
        [HttpPost]
        public ActionResult Edit(User user)
        {
            var jsonModel = new JsonModel<bool>
            {
                ErrorCode = "0",
                ErrorMessage = "",
                Result = true,
            };
            if (ModelState.IsValid)
            {
                try
                {
                    _userService.UpdateUser(user);
                }
                catch (Exception ex)
                {
                    jsonModel.ErrorCode = "-1";
                    jsonModel.ErrorMessage = ex.ToString();
                    jsonModel.Result = false;
                }
            }
            return Json(jsonModel);
        }

        // GET: User/Delete/5
        public ActionResult Delete(string id)
        {
            var jsonModel = new JsonModel<bool>
            {
                ErrorCode = "0",
                ErrorMessage = "",
                Result = true
            };
            try
            {
                _userService.DeleteUser(id);
            }
            catch (Exception ex)
            {
                jsonModel.ErrorCode = "-1";
                jsonModel.ErrorMessage = ex.ToString();
                jsonModel.Result = false;
            }
            return Json(jsonModel);
        }

        public ActionResult UserList(SortingPagingInfo info, DefaultFilter filter)
        {
            if (info.SortField == null)
            {
                info = new SortingPagingInfo
                {
                    SortField = "Id",
                    SortDirection = "ascending",
                    PageSize = CommonConstants.PAGE_SIZE,
                    CurrentPage = 1
                };
            }
            _userService.Pagination = info;
            var users = _userService.GetUsers();
            TempData["SortingPagingInfo"] = _userService.Pagination;
            return PartialView(users);
        }
    }
}

OnlineStore.Web/Views/Shared/_Advertisement.cshtml
<div class="row">
    <div class="col-sm-3">
        <div class="banner-left">
            <a href="#"><img src="~/assets/web/images/ads/ads-01.jpg" alt=""></a>
            <div class="banner-content">
                <h1>sale up to</h1>
                <h2>20% off</h2>
                <p>on selected products</p>
                <a href="#">buy now</a>
            </div>
        </div>
    </div>
    <div class="col-sm-5">
        <div class="banner banner-double"><a href="#"><img alt="" src="~/assets/web/images/ads/ads-02.jpg"></a></div>
        <div class="banner banner-double"><a href="#"><img alt="" src="~/assets/web/images/ads/ads-03.jpg"></a></div>
    </div>
    <div class="col-sm-4">
        <div class="banner"><a href="#"><img alt="" src="~/assets/web/images/ads/ads-04.jpg"></a></div>
    </div>
</div>

OnlineStore.Web/Views/Shared/_Breadcrumbs.cshtml
<div class="breadcrumbs">
    <div class="container">
        <ul class="breadcrumb">
            @Html.Action("_Breadcrumb", "Home", new { type = ViewBag.BreadcrumbType, id = ViewBag.ObjectId, title = ViewBag.Title })
        </ul>
    </div>
</div>

OnlineStore.Web/Views/Shared/_Header.cshtml
@using OnlineStore.Common
@using OnlineStore.Data.Entities
@{
    var customer = Session[CommonConstants.CUSTOMER_SESSION] as Customer;
}
<div class="header">
    <div class="topbar">
        <div class="container">
            <div class="topbar-left">
                <ul class="topbar-nav clearfix">
                    <li><a href="tel:01696911552"><span class="phone">0169 691 1552</span></a></li>
                    <li><a href="mailto:hieu.truongquan@gmail.com"><span class="email">hieu.truongquan@gmail.com</span></a></li>
                </ul>
            </div>
            <div class="topbar-right">
                <ul class="topbar-nav clearfix">
                    @if (customer == null)
                    {
                        <li><a href="/dang-ky" class="login">Đăng ký</a></li>
                        <li><a href="/dang-nhap" class="login">Đăng nhập</a></li>
                    }
                    else
                    {
                        <li class="dropdown">
                            <a href="#" class="account dropdown-toggle" data-toggle="dropdown">Xin chào, @customer.Name</a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <li><a href="/Customers/Account">Thông tin cá nhân</a></li>
                                <li><a href="/Customers/Edit/@customer.Id">Cập nhật thông tin cá nhân</a></li>
                                <li><a href="/Customers/Orders">Đơn hàng của tôi</a></li>
                                <li><a href="/Customers/Address">Địa chỉ giao hàng</a></li>
                                <li><a href="/Customers/ChangeEmail">Đổi email</a></li>
                                <li><a href="/Customers/ChangePassword">Đổi mật khẩu</a></li>
                                <li><a href="/Customers/PromotionInformation">Thông tin khuyến mại</a></li>
                                <li><a href="/Customers/Logout"><img src="~/assets/web/images/flag-spain.png" alt=""> &nbsp;Đăng xuất</a></li>
                            </ul>
                        </li>
                    }
                    <li class="dropdown">
                        <a href="#" class="currency dropdown-toggle" data-toggle="dropdown">VNĐ</a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#">Euro</a></li>
                            <li><a href="#">US Dollar</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="language dropdown-toggle" data-toggle="dropdown"><img style="width:20px;" src="~/assets/web/images/flag-vi.png" alt=""> Tiếng Việt</a>
                        <ul class="dropdown-menu dropdown-menu-right">
                            <li><a href="#"><img src="~/assets/web/images/flag-us.png" alt=""> &nbsp;English</a></li>
                            <li><a href="#"><img src="~/assets/web/images/flag-spain.png" alt=""> &nbsp;Spanish</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div><!-- /.container -->
    </div><!-- /.topbar -->
    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <a href="/" class="logo"><img src="~/assets/web/images/logo.png" alt=""></a>
                </div>
                <div class="col-md-9">
                    <div class="support-client">
                        <div class="row">
                            <div class="col-sm-4">
                                <div class="box-container time">
                                    <div class="box-inner">
                                        <h2>Thời gian làm việc</h2>
                                        <p>Thứ hai - Chủ nhật: 8.00 - 18.00</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="box-container free-shipping">
                                    <div class="box-inner">
                                        <h2>Giao hàng miễn phí</h2>
                                        <p>Với đơn hàng từ 500.000 đ trở lên</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="box-container money-back">
                                    <div class="box-inner">
                                        <h2>Hoàn trả tiền 100%</h2>
                                        <p>Trong vòng 30 ngày sau khi giao hàng</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div><!-- /.support-client -->
                    <!-- Main search -->
                    @Html.Partial("_MainSearch")

                    <!-- Mini cart -->
                    <div id="cart-container">
                        @Html.Action("_MyCart", "ShoppingCart")
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <div class="mega-container visible-lg visible-md">
                        <div class="navleft-container">
                            <div class="mega-menu-title" onclick="EnableMenu();">
                                <h3>Danh mục</h3>
                            </div>
                            <div class="mega-menu-category" style="display: none;">
                                @Html.Action("_MainMenu", "Categories")
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-9">
                    <!--Top Menu-->
                    @Html.Action("_TopMenu", "Menus")
                </div>
            </div>
        </div>

        <!-- Mobile menu -->
        @Html.Partial("_MobileMenu")

    </div><!-- /.header-bottom -->
</div><!-- /.header -->

OnlineStore.Web/Views/Shared/_HiddenSearch.cshtml
@using OnlineStore.Common
@{
    var info = (SortingPagingInfo)TempData["SortingPagingInfo"] ?? new SortingPagingInfo();
}

<div class="nav-search" id="nav-search">
    @*<span class="input-icon" style="display:none;">
            <input type="text" id="txtSearchKey" placeholder="Tìm kiếm ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
            <i class="ace-icon fa fa-search nav-search-icon"></i>
        </span>*@

    <form id="frmSearch" class="form-search">
        @*Parameters for searching*@
        <input type="hidden" name="SortField" id="hdSortField" value="@info.SortField" />
        <input type="hidden" name="SortDirection" id="hdSortDirection" value="@info.SortDirection" />
        <input type="hidden" name="TotalPages" id="hdTotalPages" value="@info.PageCount" />
        <input type="hidden" name="PageSize" id="hdPageSize" value="@info.PageSize" />
        <input type="hidden" name="CurrentPage" id="hdCurrentPage" value="@info.CurrentPage" />
        <input type="hidden" name="Keyword" id="hdKeyword" value="" />
        <input type="hidden" name="CategoryId" id="hdCategoryId" value="@ViewBag.CategoryId" />
        <input type="hidden" name="SubCategoryId" id="hdSubCategoryId" value="@ViewBag.SubCategoryId" />
        <input type="hidden" name="PriceRange" id="hdPriceRange" />
        <input type="hidden" name="Brands" id="hdBrands" />
    </form>
</div><!-- /.nav-search -->

<style>
    #frmSearch {
        border: 0px;
    }
</style>
<script type="text/javascript">
    $(document).ready(function () {
        $("#txtSearchKey").on("keyup", function (event) {
            $("#hdKeyword").val($("#txtSearchKey").val());
            if (event.keyCode === 13) {
                fnSearch();
            }
        });
    });
</script>

OnlineStore.Web/Views/Shared/_Layout.cshtml
@using OnlineStore.Web.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cửa hàng thông minh</title>

    @*@Styles.Render("~/bundles/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/script")
        @Scripts.Render("~/bundles/main")
        <script type="text/javascript">
            var appPath = '@Url.Content("~")';
            var loadingContent = '<div id="loadingContent" align="center"><img alt="" src="@Url.Content("~")Content/images/ajax-loader.gif" /></div>';
        </script>*@
    <link href="~/assets/web/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/web/css/nivo-slider.css" rel="stylesheet">
    <link href="~/assets/web/css/animate.css" rel="stylesheet">
    <link href="~/assets/web/css/owl.carousel.css" rel="stylesheet">
    <link href="~/assets/web/css/cloud-zoom.css" rel="stylesheet" />
    <link href="~/assets/web/css/style.css" rel="stylesheet">
    <link href="~/assets/web/css/jquery.bxslider.css" rel="stylesheet" />
    <link href="~/assets/web/css/responsive.css" rel="stylesheet">
    <link href="~/assets/web/css/jquery-ui.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="~/assets/web/js/jquery-1.11.0.min.js"></script>
    <script src="~/assets/web/js/jquery-ui.min.js"></script>
    <script src="~/assets/web/js/cloud-zoom.js"></script>
    <script src="~/assets/web/js/jquery.bxslider.min.js"></script>
    <script src="~/assets/web/js/jquery.nivo.slider.pack.js"></script>
    <script src="~/assets/web/js/owl.carousel.min.js"></script>
    <script src="~/assets/web/js/bootstrap.min.js"></script>
    <script src="~/assets/web/js/main.js"></script>

    <link rel="stylesheet" href="~/assets/admin/font-awesome/4.2.0/css/font-awesome.min.css" />
    
    <!--Materialize-->
    @*<script src="~/Scripts/materialize/js/materialize.min.js"></script>
    <link href="~/Scripts/materialize/css/materialize.min.css" rel="stylesheet" />*@

    <!------- Toastr ------>
    <link href="~/assets/common/js/toastr/toastr.min.css" rel="stylesheet" />
    <script src="~/assets/common/js/toastr/toastr.min.js"></script>

    <!-- select2 -->
    <link href="~/Content/css/select2.css" rel="stylesheet" />
    <script src="~/Scripts/select2.js"></script>

    <!-- ajax loading -->
    <script type="text/javascript">
        var rootPath = "@Url.Content("~")";
        var loadingContent = '<div id="loadingContent" align="center"><img alt="" width="150px" src="@Url.Content("~")assets/common/images/ajax-loader.gif" /></div>';
    </script>
</head>
@*<body>
        @Html.Action("TopMenu", "Menu")
        <div class="container body-content" id="mainContainer">
            @RenderBody()
        </div>
    
        <div id="bodyContent">
            <div id="subMenu"></div>
            <div class="body-content">
                <div id="mainContainer">
                    @RenderBody()
                </div>
            </div>
        </div>

        <div id="pageLoading" style="display: none;">
            <img width="50px" height="50px" src="@Url.Image("ajax-loader.gif")" alt="loading"/>
        </div>
    </body>*@

<body>
    @Html.Partial("_Header")
    @Html.Partial("_Breadcrumbs")
    <div id="content-container">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
</body>

</html>

OnlineStore.Web/Views/Shared/_Layout_Group.cshtml
@using OnlineStore.Web.Extensions
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cửa hàng thông minh</title>

    @*@Styles.Render("~/bundles/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/script")
        @Scripts.Render("~/bundles/main")
        <script type="text/javascript">
            var appPath = '@Url.Content("~")';
            var loadingContent = '<div id="loadingContent" align="center"><img alt="" src="@Url.Content("~")Content/images/ajax-loader.gif" /></div>';
        </script>*@
    <link href="~/assets/web/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/web/css/nivo-slider.css" rel="stylesheet">
    <link href="~/assets/web/css/animate.css" rel="stylesheet">
    <link href="~/assets/web/css/owl.carousel.css" rel="stylesheet">
    <link href="~/assets/web/css/style.css" rel="stylesheet">
    <link href="~/assets/web/css/responsive.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300,300italic,400,400italic,600,600italic,700,700italic,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
@*<body>
        @Html.Action("TopMenu", "Menu")
        <div class="container body-content" id="mainContainer">
            @RenderBody()
        </div>
    
        <div id="bodyContent">
            <div id="subMenu"></div>
            <div class="body-content">
                <div id="mainContainer">
                    @RenderBody()
                </div>
            </div>
        </div>

        <div id="pageLoading" style="display: none;">
            <img width="50px" height="50px" src="@Url.Image("ajax-loader.gif")" alt="loading"/>
        </div>
    </body>*@

<body>
    @Html.Partial("_Header")
    @RenderBody()
    @Html.Partial("_Footer")
</body>

</html>

OnlineStore.Web/Views/Shared/_MainSearch.cshtml
<form class="form-search" id="frm-main-search">
    <input type="text" class="input-text" name="Keyword" id="txtKeyword" placeholder="Tìm kiểm sản phẩm..." style="width:370px;">
    <div class="dropdown">
        @Html.Action("_CategorySelection", "Categories")
    </div>
    <button type="button" onclick="searchMain()" class="btn btn-danger"><span class="fa fa-search"></span></button>
</form>

<script>
    function searchMain()
    {
        $("#hdKeyword").val($("#txtKeyword").val());
        $("#hdCategoryId").val($("#slCategorySearch").val());
        fnSearchHome();
    }
</script>

OnlineStore.Web/Views/Shared/_TopMenu.cshtml
@using OnlineStore.Common

@if (Session[CommonConstants.USER_SESSION] != null)
{
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Quản lí quán ăn", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
                <a class="navbar-brand" href="/"><span class="glyphicon glyphicon-home"></span></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Nhà cung cấp", "Index", "Home")</li>
                    <li>@Html.ActionLink("Khách hàng", "About", "Home")</li>
                    <li>@Html.ActionLink("Quản lí bán hàng", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Quản lí mua hàng", "About", "Home")</li>
                    <li>@Html.ActionLink("Quản lí kho", "Index", "User")</li>
                    <li>@Html.ActionLink("Quản lí người dùng", "Index", "User")</li>
                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Cấu hình <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Loại chi phí", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Loại thu nhập", "Index", "Home")</li>
                            <li>@Html.ActionLink("Chủng loại", "Contact", "Home")</li>
                        </ul>
                    </li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
}